### ISSUE TITLE
Should write crossdomain.xml automatically for k8s volume.

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#1603]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `3.0.112`

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 创建k8s共享Volume，SRS和Nginx共享HLS分发目录。
1. emptyDir模式磁盘为空，Flash播放HLS时找不到crossdomain.xml。
1. 访问：http://39.107.238.185/crossdomain.xml

**期望行为(Expect)**

SRS开启HTTP Server时，在HTTP根目录，如果不存在则写入默认的crossdomain.xml。

**Comment by winlinvip** [comment]
`crossdomain.xml` can be set as default:

```
<cross-domain-policy>
  <allow-access-from domain="*"/>
</cross-domain-policy>
```

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
`index.html` can be set as default: https://github.com/ossrs/srs-docker/blob/v3/index.html

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
There is another one, console: http://localhost:1985/console

```
[root@ee1f99606509 srs]# ll objs/nginx/html/console/
-rw-r--r-- 1 root root   32 Dec 26 13:11 README.md
-rw-r--r-- 1 root root 3676 Dec 26 13:11 en_index.html
-rw-r--r-- 1 root root  263 Dec 26 13:11 index.html
drwxr-xr-x 6 root root 4096 Dec 26 13:52 js
-rw-r--r-- 1 root root 3711 Dec 26 13:11 ng_index.html
drwxr-xr-x 2 root root 4096 Dec 26 13:11 views
```

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
A simple approach is to start another container and copy the default files of SRS to the shared volume.

For example, for Deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-deployment
  labels:
    app: srs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs
  template:
    metadata:
      labels:
        app: srs
    spec:
      volumes:
      - name: cache-volume
        emptyDir: {}
      containers:
      - name: srs
        image: ossrs/srs:3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1935
        - containerPort: 1985
        - containerPort: 8080
        volumeMounts:
        - name: cache-volume
          mountPath: /usr/local/srs/objs/nginx/html
          readOnly: false
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cache-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
      - name: srs-cp-files
        image: ossrs/srs:3
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: cache-volume
          mountPath: /tmp/html
          readOnly: false
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          if [[ ! -f /tmp/html/index.html ]]; then
            cp -R ./objs/nginx/html/* /tmp/html
          fi &&
          sleep infinity
```

Among them, the `srs-cp-files` container is responsible for copying files and then sleeping continuously.

Validation successful:

* http://r.ossrs.net/
* http://r.ossrs.net/crossdomain.xml
* http://r.ossrs.net:1985/console

`TRANS_BY_GPT3`
