### ISSUE TITLE
按照官方文档自建k8s高并发集群和SRS超多推流源站集群，无法拉取HTTP-FLV流

### ISSUE THREAD

**Issue by mawenwu1983** [ossrs/srs#2038]
**描述(Description)**

> 按照官方文档在自建的k8s中搭建SRS Edge Cluster for High Concurrency Streaming和SRS Origin Cluster for a Large Number of Streams，无法通过http-flv拉流

1. SRS版本(Version): `registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4`
1. SRS的日志如下(Log):
```
2020/11/16 17:46:19 [error] 28#28: *15 open() "/usr/share/nginx/html/live/livestream/1.flv" failed (2: No such file or directory), client: 172.16.36.64, server: localhost, request: "GET /live/livestream/1.flv HTTP/1.1", host: "192.168.50.102:30080"
172.16.36.64 - - [16/Nov/2020:17:46:19 +0000] "GET /live/livestream/1.flv HTTP/1.1" 404 153 "-" "VLC/3.0.11 LibVLC/3.0.11" "-"
2020/11/16 17:46:19 [error] 28#28: *16 open() "/usr/share/nginx/html/live/livestream/1.flv" failed (2: No such file or directory), client: 172.16.36.64, server: localhost, request: "GET /live/livestream/1.flv HTTP/1.0", host: "192.168.50.102:30080"
172.16.36.64 - - [16/Nov/2020:17:46:19 +0000] "GET /live/livestream/1.flv HTTP/1.0" 404 153 "-" "VLC/3.0.11 LibVLC/3.0.11" "-"
```
1. SRS的配置如下(Config):
```
容器默认配置，没有修改
```

**重现(Replay)**

>源站集群配置
```
cat > srs-origin-cluster-for-high-concurrency-streaming.yaml << EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-origin-deploy
  labels:
    app: srs-origin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs-origin
  template:
    metadata:
      labels:
        app: srs-origin
    spec:
      volumes:
      - name: cache-volume
        emptyDir: {}
      containers:
      - name: srs
        image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1935
        - containerPort: 1985
        - containerPort: 8080
        volumeMounts:
        - name: cache-volume
          mountPath: /usr/local/srs/objs/nginx/html
          readOnly: false
      - name: nginx
        image: nginx:1.18.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cache-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
      - name: srs-cp-files
        image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: cache-volume
          mountPath: /tmp/html
          readOnly: false
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          if [[ ! -f /tmp/html/index.html ]]; then
            cp -R ./objs/nginx/html/* /tmp/html
          fi &&
          sleep infinity
---
apiVersion: v1
kind: Service
metadata:
  name: srs-origin-service
spec:
  type: ClusterIP
  selector:
    app: srs-origin
  ports:
  - name: srs-origin-service-1935-1935
    port: 1935
    protocol: TCP
    targetPort: 1935
---
apiVersion: v1
kind: Service
metadata:
  name: srs-http-service
spec:
  type: NodePort
  selector:
    app: srs-origin
  ports:
  - name: srs-http-service-80-30080
    port: 80
    nodePort: 30080
  - name: srs-http-service-1985-31985
    port: 1985
    nodePort: 31985
EOF
```
边缘集群配置
```
cat > srs-edge-cluster-for-high-concurrency-streaming.yaml << EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: srs-edge-config
data:
  srs.conf: |-
    listen              1935;
    max_connections     1000;
    daemon              off;
    http_api {
        enabled         on;
        listen          1985;
    }
    http_server {
        enabled         on;
        listen          8080;
    }
    vhost __defaultVhost__ {
        cluster {
            mode            remote;
            origin          srs-origin-service;
        }
        http_remux {
            enabled     on;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-edge-deploy
  labels:
    app: srs-edge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: srs-edge
  template:
    metadata:
      labels:
        app: srs-edge
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: srs-edge-config
      containers:
      - name: srs
        image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1935
        - containerPort: 1985
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/srs/conf
---
apiVersion: v1
kind: Service
metadata:
  name: srs-edge-service
spec:
  type: NodePort
  selector:
    app: srs-edge
  ports:
  - name: srs-edge-service-1935-31935
    port: 1935
    nodePort: 31935
  - name: srs-edge-service-8080-31080
    port: 8080
    nodePort: 31080
EOF
```

**期望行为(Expect)**

> 能拉取HTTP-FLV流
