### ISSUE TITLE
K8S: HLS Recording  caused SRS API request waiting forever

### ISSUE THREAD

**Issue by emnvn** [ossrs/srs#2246]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

I setup SRS that run inside K8S POD. Most of features worked as expected. The only thing happened when I enable HLS to record m3u8 and Segment files. These files will be write to a K8S persistent volume. 

I found that SRS successfully save these files to that volume. These files are accessible from external service (I can play .TS files with VLC program).

The issue happened when I request SRS API (http://localhost:1985/api/v1/streams) to see current streams (or any SRS Http APIs). But I can not receive the response because the request is always in waiting status. I check SRS log, I did not see this request log is displayed in SRS Log screen. I also can not access SRS Http server log at SRS default port 8080

But when I stop publishing the stream, I can receive response from these  request as normal.

I tried another location path for .TS files (It must be different from Container's mountPath) and keep .M3U8 path  then above requests worked.

I think there is some bottle neck from  write .TS files to the PersistentVolume. It blocked other SRS's HTTP request.
1. SRS版本(Version): v4.0.84
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. K8S Statefulset Config
```
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: srs-origin 
  labels:   
    app: srs-origin
spec: 
  serviceName: "socs" 
  replicas: 1
  selector:
    matchLabels:     
      app: srs-origin 
  template:   
    metadata:     
      labels:       
        app: srs-origin
    spec:
      volumes:     
        - name: recording-volume
          persistentVolumeClaim:
            claimName: pvc-origin    
        - name: config-volume
          configMap:         
            name: srs-origin-config     
      containers:     
        - name: srs      
          image: ossrs/srs:v4.0.84
          imagePullPolicy: IfNotPresent       
          ports:       
            - containerPort: 1935      
            - containerPort: 1985      
            - containerPort: 8080
            - containerPort: 8000
              protocol: UDP
     
          volumeMounts:       
            - name: recording-volume         
              mountPath: /usr/local/srs/objs/nginx/html
              readOnly: false
            - name: config-volume         
              mountPath: /usr/local/srs/conf
```
2. SRS的配置如下(Config):
```
listen           1935;    
    max_connections     1000;   
    daemon              off; 
    srs_log_level debug;
    #srs_log_file        ./objs/nginx/html/ins0.log;
    
    http_api {       
      enabled         on;       
      listen          1985;    
    }   
    http_server {       
      enabled         on;       
      listen          8080;
    }
    rtc_server {
        enabled         on;
        listen          8000;
        #candidate       127.0.0.1;
        candidate       192.168.1.14;
    }
    vhost __defaultVhost__ { 
      rtc {
        enabled     on;
        bframe      discard;
    }
    tcp_nodelay     on;
    min_latency     on;
    play {
        gop_cache       off;
        queue_length    10;
        #mw_latency      100;
        mw_latency      100;
    }
    publish {
        mr off;
    }      
      cluster {           
        origin_cluster  on;
          #coworkers       srs-origin-0.socs;  
          coworkers       srs-origin-0.socs:1985 srs-origin-1.socs:1986 srs-origin-2.socs:1987;      
        }       
        http_remux {           
          enabled     off;       
          }
          dvr {
        enabled      on;
        dvr_path     ./objs/nginx/html/ins0_dvr/[app]/[stream].[timestamp].flv;
        dvr_plan     session;
    }     
         hls {          
          enabled         on;
          hls_fragment 3;
        hls_window 60;
        hls_m3u8_file ins0/[app]/[stream].m3u8;
        hls_ts_file ins0/[app]/[stream]-[seq].ts;  
          }    
          }
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. Publish stream to SRS
1. Waiting for the first .TS file wrote to disk
1. Request api: http://localhost:1985/api/v1/streams (or any SRS API)
1. Receive response

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

I can request SRS APIs as normal
