### ISSUE TITLE
docker-compose启动srs和独立的http hook的server, srs.conf中用容器名配置callback,不work

### ISSUE THREAD

**Issue by xupeng1206** [ossrs/srs#2576]
**描述(Description)**

> docker-compose启动srs和独立的http hook的server, srs.conf中用容器名配置callback,不work,必须指定ip才能work

1. SRS版本(Version): `4.0release`

2. SRS的日志如下(Log):
![image](https://user-images.githubusercontent.com/30151441/131941819-89caf89c-8f89-4e98-96ad-33bc7096ffa5.png)
![image](https://user-images.githubusercontent.com/30151441/131941901-af1c2080-e5b4-4a7b-80f9-b502a2527118.png)

3. SRS的配置如下(Config):
docker-compose.yml:
```
version: "2"
services:
  srs:
    image: srs:local
    container_name: srs
    restart: always
    command: bash -c "/usr/local/srs/objs/srs -c /usr/local/srs/conf/srs.conf"
    environment:
      - CANDIDATE=192.168.2.110
    ports:
      - 1935:1935
      - 8080:8080
      - 1985:1985
      - 8000:8000/udp
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
      - ./live:/usr/local/srs/objs/nginx/html/live
    depends_on:
      - srs_hooks
  srs_hooks:
    image: srs_hooks:local
    container_name: srs_hooks
    restart: always
    environment:
      - CONFIG_FILE=/root/config.ini
    ports:
      - 8085:8085
    volumes:
      - ./logs:/root/logs
      - ./config.ini:/root/config.ini
```
srs.conf
```
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
srs_log_tank        console;
daemon              off;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
rtc_server {
    enabled         on;
    # Listen at udp://8000
    listen          8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/issues/307#issuecomment-599028124
    candidate       $CANDIDATE;
}
vhost __defaultVhost__ {
    tcp_nodelay     on
    min_latency     on;

    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        bframe      discard;
    }

    play {
        gop_cache       off;
        queue_length    10;
        mw_latency      100;
    }

    publish {
        mr off;
        # mr_latency 100;
    }

    http_hooks{
        enabled       on;
        on_connect    http://srs_hooks:8085/api/srs/hooks/connect;
    }
}
```

**重现(Replay)**
1. docker-compose up -d
2. ffmpeg 推流

**期望行为(Expect)**

> 希望在配置文件里支持用容器名
