### ISSUE TITLE
[K8S] k8s的 deployment，貌似跑不起来

### ISSUE THREAD

**Issue by jinleileiking** [ossrs/srs#2625]
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-deploy
  labels:
    app: srs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs
  template:
    metadata:
      labels:
        app: srs
    spec:
      containers:
      - name: srs
        image: ossrs/srs:3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1935
        - containerPort: 1985
        - containerPort: 8080
EOF
```

这个的dockerfile，貌似没用daemon off，在我的环境跑起来就挂了，一直拉不起来
