### ISSUE TITLE
http_hooks always connect to localhost on Docker compose

### ISSUE THREAD

**Issue by vbph** [ossrs/srs#4048]
**Version:** ossrs/srs:5 Docker image

I run SRS locally via docker-compose for testing but the my `http_hooks` seems not to work.

`http_hooks` callbacks to my local server listening port `3000`. However, there were no requests my server when I started to stream from OBS. And I was still able to do this even when I shutdowned my server.

<img width="690" alt="Screenshot 2024-05-01 at 14 15 33" src="https://github.com/ossrs/srs/assets/114387406/b8bbac03-2dfd-40fa-9c5a-d2e3186a6862">

### `srs.conf`
```
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
vhost __defaultVhost__ {
    http_hooks {
        enabled         on;
        on_publish      http://localhost:3000/live/start;
        on_unpublish    http://localhost:3000/live/end;
        on_play         http://localhost:3000/live/play;
        on_stop         http://localhost:3000/live/stop;
    }
}
```

### `compose.yaml`
```
name: dev

services:
    redis:
        container_name: cache
        image: redis
        ports:
            - 6379:6379
        volumes:
            - redis:/data

    rtmp:
        container_name: rtmp
        image: ossrs/srs:5
        volumes:
            - ./srs.conf:/usr/local/srs/conf/srs.conf
        network_mode: host

volumes:
    redis:
        driver: local
```

I placed the `srs.conf` file in the same directory of `compose.yaml` and it's definitely mounted to the container.

```
$ docker exec -it rtmp /bin/bash    
$ root@orbstack:/usr/local/srs# cat /usr/local/srs/conf/srs.conf
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
vhost __defaultVhost__ {
    http_hooks {
        enabled         on;
        on_publish      http://localhost:3000/live/start;
        on_unpublish    http://localhost:3000/live/end;
        on_play         http://localhost:3000/live/play;
        on_stop         http://localhost:3000/live/stop;
    }
}
```
